name = "stt-assembly-ner"
account_id = "1a481f7cdb7027c30174a692c89cbda1"
# route = { pattern = "stt-assembly-ner.voitherbrazil.workers.dev/*", zone_name = "voitherbrazil.workers.dev" }
compatibility_date = "2024-11-01"
main = "src/index.ts"

[vars]
ENVIRONMENT = "production"
AZURE_AI_ENDPOINT = "https://textanalytics-stt-voither.cognitiveservices.azure.com/"
AZURE_AI_API_VERSION = "2023-04-01"
OPENAI_API_ENDPOINT = "https://api.openai.com"
MAX_RETRIES = "3"
TIMEOUT_MS = "600000"

# Secrets configured via: wrangler secret put <SECRET_NAME>
# AZURE_AI_API_KEY
# OPENAI_API_KEY
# INTER_WORKER_TOKEN
# ADMIN_API_KEY

[[kv_namespaces]]
binding = "STT_JOBS"
id = "0c67436e3e304e1eb111f20b6b951928"
preview_id = "596acaf3c2d14ce2b1aef43d1eed2a36"

[[r2_buckets]]
binding = "RESULTS_STORAGE"
bucket_name = "stt-results"
preview_bucket_name = "stt-results-dev"

[env.development.vars]
ENVIRONMENT = "development"
AZURE_AI_ENDPOINT = "https://textanalytics-stt-voither.cognitiveservices.azure.com/"

[env.staging.vars]
ENVIRONMENT = "staging"